backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "globalPreferences"
    label: "Global Preferences"
    editor:
      preview: false
    files:
      - label: "General Settings"
        name: "generalSettings"
        file: "src/data/gen.yaml"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generalSettings"}
          - label: "Social Links"
            name: "socialLinks"
            widget: "object"
            fields:
              - {label: "GitHub Url", name: "githubUrl", widget: "string", required: false}
              - {label: "LinkedIn Url", name: "linkedinUrl", widget: "string", required: false}
              - {label: "Site Logo", name: "siteLogo", widget: "image", required: false}
          - label: 'Shape Colors'
            name: shapeColors
            widget: object
            fields:
              [
                {
                  label: 'Foreground Blob',
                  name: foregroundBlob,
                  widget: object,
                  fields:
                    [
                      {label: 'Top Color', name: topColor, widget: string},
                      {label: 'Bottom Color', name: bottomColor, widget: string}
                    ]
                },
                {
                  label: 'Background Blob',
                  name: backgroundBlob,
                  widget: object,
                  fields:
                    [
                      {label: 'Top Color', name: topColor, widget: string},
                      {label: 'Bottom Color', name: bottomColor, widget: string}
                    ]
                },
                {
                  label: Rectangle,
                  name: rectangle,
                  widget: object,
                  fields:
                    [
                      {label: 'Background', name: background, widget: string},
                      {label: 'Outline', name: outline, widget: string}
                    ]
                }
              ]
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Project", name: "featuredProject", widget: "boolean"}
      - {label: "Project Date", name: "projectDate", widget: "datetime"}
      - {label: "Project Image", name: "projectImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}    
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - label: Icons,
            name: icons,
            widget: list,
            fields:
              [
                {label: Image, name: image, widget: image},
                {label: Alt Text, name: altText, widget: string}
              ]
          - label: Tiles,
            name: tiles,
            widget: list,
            fields:
              [  
                {label: Image, name: image, widget: image},
                {label: Content, name: content, widget: markdown},
              ] 
          - label: 'SEO Metadata'
            name: seoMetadata,
            widget: object,
            fields: 
              [
                {label: 'Html Title', name: htmlTitle, widget: string},
                {label: 'Meta Description', name: metaDescription, widget: string}
              ]
      - file: "src/pages/projects/index.md"
        label: "Projects Page"
        name: "projects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projects-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
